/**
 * Cross-platform compatibility helpers for the judge.
 *
 * Apple's clang (which is what `g++` usually points to on macOS) ships without
 * `<bits/stdc++.h>`, a header that most competitive programmers use by default.
 * When the configured compiler cannot find it we generate a drop-in shim and
 * add its directory to the include path, so the same source file compiles on
 * Linux and macOS.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { config } from '../config.js';

const SHIM_HEADER = `// Generated by OGOJ - a portable stand-in for GCC's <bits/stdc++.h>.
#ifndef OGOJ_BITS_STDCPP_H
#define OGOJ_BITS_STDCPP_H

#include <algorithm>
#include <array>
#include <atomic>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <cfenv>
#include <chrono>
#include <cinttypes>
#include <climits>
#include <cmath>
#include <complex>
#include <csetjmp>
#include <csignal>
#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <exception>
#include <forward_list>
#include <fstream>
#include <functional>
#include <future>
#include <iomanip>
#include <initializer_list>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <istream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <mutex>
#include <new>
#include <numeric>
#include <ostream>
#include <queue>
#include <random>
#include <ratio>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <streambuf>
#include <string>
#include <string_view>
#include <system_error>
#include <thread>
#include <tuple>
#include <type_traits>
#include <typeindex>
#include <typeinfo>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

#endif
`;

interface CompatState {
  checked: boolean;
  includeDir: string | null;
}

const state: CompatState = { checked: false, includeDir: null };

function compilerSupports(compiler: string, header: string): boolean {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ogoj-probe-'));
  try {
    const source = path.join(dir, 'probe.cpp');
    fs.writeFileSync(source, `#include <${header}>\nint main() { return 0; }\n`, 'utf8');
    const result = spawnSync(compiler, ['-fsyntax-only', 'probe.cpp'], {
      cwd: dir,
      encoding: 'utf8',
      timeout: 20000,
    });
    return result.status === 0;
  } catch {
    return false;
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

/**
 * Returns the extra include directory needed to compile `#include <bits/stdc++.h>`,
 * or `null` when the compiler already supports it.
 */
export function bitsIncludeDir(compiler: string): string | null {
  if (state.checked) return state.includeDir;
  state.checked = true;
  if (compilerSupports(compiler, 'bits/stdc++.h')) {
    state.includeDir = null;
    return null;
  }
  const dir = path.join(config.paths.judge, 'include', 'bits');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'stdc++.h'), SHIM_HEADER, 'utf8');
  state.includeDir = path.join(config.paths.judge, 'include');
  return state.includeDir;
}

export function resetCompatCache(): void {
  state.checked = false;
  state.includeDir = null;
}
