/**
 * Every tunable option of the site is declared here once and then rendered
 * automatically by the super-admin control panel (/admin/settings).
 *
 * - `public: true`  -> exposed to the frontend through GET /api/settings
 * - `secret: true`  -> never sent to the browser, masked in the admin UI
 */
export type SettingType =
  | 'string'
  | 'text'
  | 'number'
  | 'boolean'
  | 'select'
  | 'color'
  | 'password'
  | 'json'
  | 'image';

export interface SettingField {
  key: string;
  label: string;
  type: SettingType;
  default: string | number | boolean;
  group: string;
  description?: string;
  options?: { value: string; label: string }[];
  min?: number;
  max?: number;
  step?: number;
  public?: boolean;
  secret?: boolean;
  placeholder?: string;
  /** Upload sub-directory used by `type: 'image'` fields. */
  uploadCategory?: string;
}

export interface SettingGroup {
  key: string;
  name: string;
  description: string;
  icon: string;
}

export const SETTING_GROUPS: SettingGroup[] = [
  {
    key: 'site',
    name: '站点信息',
    description: '站点名称、Logo、描述等基础信息',
    icon: 'globe',
  },
  {
    key: 'appearance',
    name: '外观布局',
    description: '主题色、首页模块、轮播图与页脚展示',
    icon: 'palette',
  },
  {
    key: 'account',
    name: '注册与登录',
    description: '注册开关、用户名规则、会话与登录安全',
    icon: 'user-plus',
  },
  {
    key: 'user',
    name: '用户与权限',
    description: '角色、等级、个人主页可见性与昵称规则',
    icon: 'users',
  },
  {
    key: 'problem',
    name: '题库与题目',
    description: '题目默认限制、编号规则、题解与标签策略',
    icon: 'book',
  },
  {
    key: 'judge',
    name: '评测设置',
    description: '评测机并发、编译器、比对方式与错误重试',
    icon: 'cpu',
  },
  {
    key: 'submission',
    name: '提交限制',
    description: '提交频率、代码长度、公开展示策略',
    icon: 'send',
  },
  {
    key: 'contest',
    name: '比赛设置',
    description: '赛制、报名、排行榜与用户自建比赛规则',
    icon: 'trophy',
  },
  {
    key: 'community',
    name: '讨论与社区',
    description: '讨论区、题解、文章广场、评论与敏感词',
    icon: 'messages-square',
  },
  {
    key: 'points',
    name: '积分与商店',
    description: '积分产出与消耗、商店商品与兑换规则',
    icon: 'shopping-bag',
  },
  {
    key: 'security',
    name: '安全防护',
    description: '限流、验证码、上传限制与维护模式',
    icon: 'shield',
  },
  {
    key: 'mail',
    name: '邮件通知',
    description: 'SMTP 配置与通知策略',
    icon: 'mail',
  },
  {
    key: 'legal',
    name: '页脚与备案',
    description: '备案号、版权信息与自定义链接',
    icon: 'scale',
  },
  {
    key: 'maintenance',
    name: '备份与维护',
    description: '自动备份、缓存与数据清理',
    icon: 'database',
  },
  {
    key: 'oauth',
    name: '第三方登录',
    description: 'GitHub / Gitee / Google / 自定义 OAuth2 登录与账号绑定',
    icon: 'key-round',
  },
  {
    key: 'achievement',
    name: '成就徽章',
    description: '徽章解锁条件、奖励与通知',
    icon: 'award',
  },
  {
    key: 'ticket',
    name: '工单与支持',
    description: '用户工单提交、处理流程与通知',
    icon: 'life-buoy',
  },
];

const langOptions = [
  { value: 'c', label: 'C' },
  { value: 'cpp', label: 'C++' },
  { value: 'cpp14', label: 'C++14' },
  { value: 'cpp17', label: 'C++17' },
  { value: 'cpp20', label: 'C++20' },
  { value: 'python3', label: 'Python 3' },
  { value: 'pypy3', label: 'PyPy 3' },
  { value: 'java', label: 'Java' },
  { value: 'node', label: 'JavaScript (Node)' },
  { value: 'go', label: 'Go' },
  { value: 'rust', label: 'Rust' },
];

export const SETTINGS: SettingField[] = [
  // ---------------------------------------------------------------- site
  {
    key: 'site_name',
    label: '站点名称',
    type: 'string',
    default: 'OGOJ',
    group: 'site',
    description: '显示在左上角与浏览器标题中的名称，例如 OGOJ',
    public: true,
  },
  {
    key: 'site_full_name',
    label: '站点全称',
    type: 'string',
    default: 'Oganesson Online Judge',
    group: 'site',
    description: '完整的站点英文名，用于页脚与 SEO',
    public: true,
  },
  {
    key: 'site_description',
    label: '站点简介',
    type: 'text',
    default: 'OGOJ 是一个开放、自由、功能完整的在线评测系统。',
    group: 'site',
    public: true,
  },
  {
    key: 'site_keywords',
    label: 'SEO 关键词',
    type: 'string',
    default: 'OGOJ,在线评测,Online Judge,Oganesson',
    group: 'site',
  },
  {
    key: 'site_logo',
    label: '站点 Logo',
    type: 'image',
    default: '',
    group: 'site',
    description: '可直接上传图片，留空则显示文字 Logo',
    public: true,
    uploadCategory: 'site',
  },
  {
    key: 'site_favicon',
    label: '站点图标 (favicon)',
    type: 'image',
    default: '',
    group: 'site',
    public: true,
    uploadCategory: 'site',
  },
  {
    key: 'site_url',
    label: '站点地址',
    type: 'string',
    default: 'http://localhost:8080',
    group: 'site',
    description: '用于生成绝对链接，例如 OJ 比赛提醒',
  },
  {
    key: 'contact_email',
    label: '联系邮箱',
    type: 'string',
    default: '',
    group: 'site',
    public: true,
  },
  {
    key: 'github_url',
    label: 'GitHub 仓库地址',
    type: 'string',
    default: 'https://github.com/x4ce-organization/OGOJ',
    group: 'site',
    description: '左上角 OGOJ 文字点击后跳转的地址',
    public: true,
  },
  {
    key: 'icp_record',
    label: 'ICP 备案号',
    type: 'string',
    default: '',
    group: 'site',
    public: true,
  },
  {
    key: 'police_record',
    label: '公安备案号',
    type: 'string',
    default: '',
    group: 'site',
    public: true,
  },

  // ---------------------------------------------------------- appearance
  {
    key: 'theme_color',
    label: '主题色',
    type: 'color',
    default: '#0ea5e9',
    group: 'appearance',
    description: '全站主色调（按钮、链接、高亮）',
    public: true,
  },
  {
    key: 'default_theme_mode',
    label: '默认配色模式',
    type: 'select',
    default: 'light',
    group: 'appearance',
    options: [
      { value: 'light', label: '浅色' },
      { value: 'dark', label: '深色' },
      { value: 'system', label: '跟随系统' },
    ],
    public: true,
  },
  {
    key: 'enable_dark_mode',
    label: '允许用户切换深色模式',
    type: 'boolean',
    default: true,
    group: 'appearance',
    public: true,
  },
  {
    key: 'layout_width',
    label: '页面宽度',
    type: 'select',
    default: 'wide',
    group: 'appearance',
    options: [
      { value: 'normal', label: '标准 (1200px)' },
      { value: 'wide', label: '宽屏 (1440px)' },
      { value: 'full', label: '全宽' },
    ],
    public: true,
  },
  {
    key: 'enable_carousel',
    label: '首页显示轮播图',
    type: 'boolean',
    default: true,
    group: 'appearance',
    public: true,
  },
  {
    key: 'home_hero_image',
    label: '首页首屏大图',
    type: 'image',
    default: '',
    group: 'appearance',
    description: '显示在首页顶部（轮播关闭时作为主视觉图），留空使用主题渐变背景',
    public: true,
    uploadCategory: 'site',
  },
  {
    key: 'home_background_image',
    label: '首页背景图',
    type: 'image',
    default: '',
    group: 'appearance',
    description: '平铺在首页内容区底层的背景图，留空使用默认纯色',
    public: true,
    uploadCategory: 'site',
  },
  {
    key: 'carousel_interval',
    label: '轮播切换间隔（秒）',
    type: 'number',
    default: 6,
    min: 2,
    max: 60,
    group: 'appearance',
    public: true,
  },
  {
    key: 'home_notice',
    label: '首页顶部公告条',
    type: 'text',
    default: '欢迎来到 OGOJ！做完一道题即可获得积分，积分可在商店兑换创建比赛、出题等特权。',
    group: 'appearance',
    public: true,
  },
  {
    key: 'show_home_modules',
    label: '首页显示的模块',
    type: 'json',
    default: '["carousel","notice","statistics","recent_problems","recent_contests","recent_discussions","ranklist"]',
    group: 'appearance',
    description: 'JSON 数组，可选：carousel, notice, statistics, recent_problems, recent_contests, recent_discussions, ranklist, tags',
    public: true,
  },
  {
    key: 'footer_text',
    label: '页脚文字',
    type: 'string',
    default: 'Powered by OGOJ',
    group: 'appearance',
    description: '页面最下方显示的版权文字',
    public: true,
  },
  {
    key: 'footer_links',
    label: '页脚链接',
    type: 'json',
    default: '[{"label":"关于本站","href":"/about"},{"label":"帮助","href":"/help"},{"label":"开源仓库","href":"https://github.com/x4ce-organization/OGOJ"}]',
    group: 'appearance',
    public: true,
  },
  {
    key: 'show_github_link',
    label: '显示 GitHub 图标',
    type: 'boolean',
    default: true,
    group: 'appearance',
    public: true,
  },

  // ------------------------------------------------------------- account
  {
    key: 'allow_register',
    label: '开放注册',
    type: 'boolean',
    default: true,
    group: 'account',
    public: true,
  },
  {
    key: 'register_need_invite',
    label: '注册需要邀请码',
    type: 'boolean',
    default: false,
    group: 'account',
    public: true,
  },
  {
    key: 'invite_code',
    label: '全站邀请码',
    type: 'string',
    default: '',
    group: 'account',
    secret: true,
  },
  {
    key: 'register_email_suffix',
    label: '注册邮箱后缀白名单',
    type: 'json',
    default: '[]',
    group: 'account',
    description: '例如 ["qq.com","163.com"]，空数组表示不限制',
    public: true,
  },
  {
    key: 'register_need_email',
    label: '注册必须填写邮箱',
    type: 'boolean',
    default: false,
    group: 'account',
  },
  {
    key: 'username_min_length',
    label: '用户名最短长度',
    type: 'number',
    default: 3,
    min: 1,
    max: 32,
    group: 'account',
    public: true,
  },
  {
    key: 'username_max_length',
    label: '用户名最长长度',
    type: 'number',
    default: 16,
    min: 4,
    max: 64,
    group: 'account',
    public: true,
  },
  {
    key: 'username_regex',
    label: '用户名正则',
    type: 'string',
    default: '^[A-Za-z0-9_\\u4e00-\\u9fa5-]{1,32}$',
    group: 'account',
  },
  {
    key: 'password_min_length',
    label: '密码最短长度',
    type: 'number',
    default: 8,
    min: 4,
    max: 64,
    group: 'account',
    public: true,
  },
  {
    key: 'banned_usernames',
    label: '禁止注册的用户名',
    type: 'json',
    default: '["admin","administrator","root","system","ogoj","official","support","moderator"]',
    group: 'account',
  },
  {
    key: 'default_role',
    label: '新用户默认角色',
    type: 'select',
    default: 'user',
    group: 'account',
    options: [
      { value: 'user', label: '普通用户' },
      { value: 'admin', label: '普通管理员' },
    ],
  },
  {
    key: 'session_days',
    label: '登录状态保持天数',
    type: 'number',
    default: 14,
    min: 1,
    max: 365,
    group: 'account',
  },
  {
    key: 'login_fail_limit',
    label: '登录失败次数上限',
    type: 'number',
    default: 10,
    min: 0,
    max: 100,
    group: 'account',
    description: '超过次数后临时锁定账号，0 表示不限制',
  },
  {
    key: 'login_lock_minutes',
    label: '登录锁定时长（分钟）',
    type: 'number',
    default: 15,
    min: 1,
    max: 1440,
    group: 'account',
  },
  {
    key: 'enable_captcha',
    label: '启用图形验证码',
    type: 'boolean',
    default: false,
    group: 'account',
    public: true,
  },

  // ---------------------------------------------------------------- user
  {
    key: 'allow_change_username',
    label: '允许用户修改用户名',
    type: 'boolean',
    default: false,
    group: 'user',
    public: true,
  },
  {
    key: 'allow_user_homepage',
    label: '开放个人主页',
    type: 'boolean',
    default: true,
    group: 'user',
    public: true,
  },
  {
    key: 'hide_private_by_default',
    label: '默认隐藏提交记录与通过题目',
    type: 'boolean',
    default: false,
    group: 'user',
  },
  {
    key: 'show_rating',
    label: '显示用户等级分',
    type: 'boolean',
    default: true,
    group: 'user',
    public: true,
  },
  {
    key: 'allow_follow',
    label: '允许关注功能',
    type: 'boolean',
    default: true,
    group: 'user',
    public: true,
  },
  {
    key: 'level_names',
    label: '等级名称',
    type: 'json',
    default: '["新手上路","初级选手","中级选手","高级选手","资深选手","金牌选手","大师","宗师","传说"]',
    group: 'user',
    description: '按通过题数自动计算的等级称号',
    public: true,
  },
  {
    key: 'level_thresholds',
    label: '等级门槛（通过题数）',
    type: 'json',
    default: '[0,5,20,50,100,200,400,700,1000]',
    group: 'user',
    public: true,
  },
  {
    key: 'user_list_page_size',
    label: '用户列表每页数量',
    type: 'number',
    default: 50,
    min: 10,
    max: 200,
    group: 'user',
  },

  // ------------------------------------------------------------- problem
  {
    key: 'problem_id_prefix',
    label: '题目编号前缀',
    type: 'string',
    default: 'P',
    group: 'problem',
    description: '题目显示编号形如 P1001',
    public: true,
  },
  {
    key: 'problem_id_start',
    label: '题目编号起始值',
    type: 'number',
    default: 1001,
    min: 1,
    max: 1000000,
    group: 'problem',
  },
  {
    key: 'default_time_limit',
    label: '默认时间限制 (ms)',
    type: 'number',
    default: 1000,
    min: 100,
    max: 20000,
    group: 'problem',
  },
  {
    key: 'default_memory_limit',
    label: '默认内存限制 (MB)',
    type: 'number',
    default: 256,
    min: 16,
    max: 4096,
    group: 'problem',
  },
  {
    key: 'max_time_limit',
    label: '最大时间限制 (ms)',
    type: 'number',
    default: 10000,
    min: 1000,
    max: 60000,
    group: 'problem',
  },
  {
    key: 'max_memory_limit',
    label: '最大内存限制 (MB)',
    type: 'number',
    default: 1024,
    min: 64,
    max: 8192,
    group: 'problem',
  },
  {
    key: 'problem_list_page_size',
    label: '题库每页数量',
    type: 'number',
    default: 50,
    min: 10,
    max: 200,
    group: 'problem',
    public: true,
  },
  {
    key: 'show_problem_tags',
    label: '题面显示算法标签',
    type: 'boolean',
    default: true,
    group: 'problem',
    public: true,
  },
  {
    key: 'show_problem_source',
    label: '题面显示题目来源',
    type: 'boolean',
    default: true,
    group: 'problem',
    public: true,
  },
  {
    key: 'show_accepted_count',
    label: '题库列表显示通过率',
    type: 'boolean',
    default: true,
    group: 'problem',
    public: true,
  },
  {
    key: 'enable_difficulty_vote',
    label: '允许用户投票题目难度',
    type: 'boolean',
    default: true,
    group: 'problem',
    public: true,
  },
  {
    key: 'allow_user_create_problem',
    label: '允许用户通过商店出题',
    type: 'boolean',
    default: true,
    group: 'problem',
    public: true,
  },
  {
    key: 'user_problem_need_review',
    label: '用户题目需要管理员审核',
    type: 'boolean',
    default: true,
    group: 'problem',
  },
  {
    key: 'allow_download_testdata',
    label: '允许下载测试数据',
    type: 'boolean',
    default: false,
    group: 'problem',
    public: true,
  },
  {
    key: 'enable_spj',
    label: '允许使用 Special Judge',
    type: 'boolean',
    default: true,
    group: 'problem',
  },
  {
    key: 'enable_interactive',
    label: '允许交互题',
    type: 'boolean',
    default: true,
    group: 'problem',
  },

  // --------------------------------------------------------------- judge
  {
    key: 'judge_concurrency',
    label: '评测并发数',
    type: 'number',
    default: 2,
    min: 1,
    max: 64,
    group: 'judge',
    description: '本机同时评测的提交数量',
  },
  {
    key: 'enabled_languages',
    label: '启用的语言',
    type: 'json',
    default: '["c","cpp","cpp14","cpp17","python3","java","node"]',
    group: 'judge',
    description: 'JSON 数组，决定提交页可选语言',
    public: true,
  },
  {
    key: 'compare_mode',
    label: '默认答案比对方式',
    type: 'select',
    default: 'trim',
    group: 'judge',
    options: [
      { value: 'strict', label: '逐字节比较' },
      { value: 'trim', label: '忽略行末空格与末尾换行' },
      { value: 'token', label: '忽略所有空白字符' },
    ],
  },
  {
    key: 'judge_priority_boost',
    label: '比赛提交优先评测',
    type: 'boolean',
    default: true,
    group: 'judge',
  },
  {
    key: 'compile_timeout_ms',
    label: '编译超时 (ms)',
    type: 'number',
    default: 15000,
    min: 1000,
    max: 120000,
    group: 'judge',
  },
  {
    key: 'judge_retry_times',
    label: '系统错误自动重测次数',
    type: 'number',
    default: 1,
    min: 0,
    max: 5,
    group: 'judge',
  },
  {
    key: 'time_multiplier',
    label: '时间限制倍率',
    type: 'number',
    default: 1,
    min: 0.5,
    max: 5,
    step: 0.1,
    group: 'judge',
    description: '评测时实际时限 = 题目时限 × 倍率',
  },
  {
    key: 'output_limit_kb',
    label: '输出长度上限 (KB)',
    type: 'number',
    default: 64,
    min: 1,
    max: 1024,
    group: 'judge',
  },
  {
    key: 'show_judge_detail',
    label: '向用户展示每个测试点结果',
    type: 'boolean',
    default: true,
    group: 'judge',
    public: true,
  },
  {
    key: 'show_testcase_data',
    label: '向提交者展示测试点输入输出',
    type: 'boolean',
    default: false,
    group: 'judge',
    public: true,
  },
  {
    key: 'rejudge_on_problem_update',
    label: '题目数据更新后自动重测',
    type: 'boolean',
    default: false,
    group: 'judge',
  },
  {
    key: 'special_judge_default',
    label: '默认开启 Special Judge',
    type: 'boolean',
    default: false,
    group: 'judge',
  },

  // ---------------------------------------------------------- submission
  {
    key: 'allow_submit',
    label: '允许提交代码',
    type: 'boolean',
    default: true,
    group: 'submission',
    public: true,
  },
  {
    key: 'submit_interval_seconds',
    label: '两次提交最小间隔（秒）',
    type: 'number',
    default: 3,
    min: 0,
    max: 600,
    group: 'submission',
    public: true,
  },
  {
    key: 'max_submissions_per_day',
    label: '每日提交上限',
    type: 'number',
    default: 0,
    min: 0,
    max: 10000,
    group: 'submission',
    description: '0 表示不限制',
  },
  {
    key: 'max_code_size_kb',
    label: '代码长度上限 (KB)',
    type: 'number',
    default: 64,
    min: 1,
    max: 1024,
    group: 'submission',
    public: true,
  },
  {
    key: 'show_others_code',
    label: '允许查看他人代码',
    type: 'boolean',
    default: true,
    group: 'submission',
    public: true,
  },
  {
    key: 'show_others_code_need_ac',
    label: '通过题目后才能查看他人代码',
    type: 'boolean',
    default: false,
    group: 'submission',
  },
  {
    key: 'submission_page_size',
    label: '评测记录每页数量',
    type: 'number',
    default: 50,
    min: 10,
    max: 200,
    group: 'submission',
    public: true,
  },
  {
    key: 'record_default_filter',
    label: '默认记录筛选',
    type: 'select',
    default: 'all',
    group: 'submission',
    options: [
      { value: 'all', label: '全部' },
      { value: 'mine', label: '我的' },
    ],
    public: true,
  },

  // ------------------------------------------------------------- contest
  {
    key: 'default_contest_rules',
    label: '默认赛制',
    type: 'select',
    default: 'acm',
    group: 'contest',
    options: [
      { value: 'acm', label: 'ACM（按题目通过数与罚时排名）' },
      { value: 'oi', label: 'OI（按分数排名，赛时隐藏排名）' },
      { value: 'ioi', label: 'IOI（按分数排名，实时显示）' },
    ],
    public: true,
  },
  {
    key: 'allow_user_contest',
    label: '允许用户通过商店创建比赛',
    type: 'boolean',
    default: true,
    group: 'contest',
    public: true,
  },
  {
    key: 'user_contest_need_review',
    label: '用户比赛需要管理员审核',
    type: 'boolean',
    default: true,
    group: 'contest',
  },
  {
    key: 'user_contest_max_days',
    label: '用户比赛最长时长（天）',
    type: 'number',
    default: 7,
    min: 1,
    max: 60,
    group: 'contest',
    public: true,
  },
  {
    key: 'contest_default_duration',
    label: '默认比赛时长（分钟）',
    type: 'number',
    default: 180,
    min: 10,
    max: 20160,
    group: 'contest',
    public: true,
  },
  {
    key: 'contest_list_page_size',
    label: '比赛列表每页数量',
    type: 'number',
    default: 20,
    min: 5,
    max: 100,
    group: 'contest',
    public: true,
  },
  {
    key: 'contest_need_register_default',
    label: '新比赛默认需要报名',
    type: 'boolean',
    default: true,
    group: 'contest',
  },
  {
    key: 'contest_show_rank_default',
    label: '新比赛默认公开排行榜',
    type: 'boolean',
    default: true,
    group: 'contest',
  },
  {
    key: 'contest_freeze_default',
    label: '新比赛默认封榜时长（分钟）',
    type: 'number',
    default: 0,
    min: 0,
    max: 1440,
    group: 'contest',
  },
  {
    key: 'contest_allow_star',
    label: '允许非正式参赛（Star）',
    type: 'boolean',
    default: true,
    group: 'contest',
    public: true,
  },
  {
    key: 'rating_contest_weight',
    label: '比赛积分权重',
    type: 'number',
    default: 1,
    min: 0,
    max: 10,
    step: 0.1,
    group: 'contest',
    description: '比赛结束后按排名发放积分的倍率',
  },
  {
    key: 'contest_rank_show_self_only',
    label: '比赛进行中只显示自己的排名',
    type: 'boolean',
    default: false,
    group: 'contest',
  },

  // ----------------------------------------------------------- community
  {
    key: 'enable_discussion',
    label: '开启讨论区',
    type: 'boolean',
    default: true,
    group: 'community',
    public: true,
  },
  {
    key: 'enable_problem_discussion',
    label: '开启题目讨论区',
    type: 'boolean',
    default: true,
    group: 'community',
    public: true,
  },
  {
    key: 'enable_solution',
    label: '开启题解功能',
    type: 'boolean',
    default: true,
    group: 'community',
    public: true,
  },
  {
    key: 'solution_need_approved',
    label: '题解需管理员审核后公开',
    type: 'boolean',
    default: false,
    group: 'community',
  },
  {
    key: 'enable_article',
    label: '开启文章广场',
    type: 'boolean',
    default: true,
    group: 'community',
    public: true,
  },
  {
    key: 'enable_comment',
    label: '开启评论功能',
    type: 'boolean',
    default: true,
    group: 'community',
    public: true,
  },
  {
    key: 'enable_private_message',
    label: '开启私信功能',
    type: 'boolean',
    default: true,
    group: 'community',
    description: '用户之间可以互相发送私信',
    public: true,
  },
  {
    key: 'pm_rate_limit_seconds',
    label: '两次发送私信的最小间隔（秒）',
    type: 'number',
    default: 10,
    min: 0,
    max: 3600,
    group: 'community',
  },
  {
    key: 'pm_max_length',
    label: '单条私信长度上限（字符）',
    type: 'number',
    default: 2000,
    min: 100,
    max: 20000,
    group: 'community',
    public: true,
  },
  {
    key: 'discussion_page_size',
    label: '讨论列表每页数量',
    type: 'number',
    default: 30,
    min: 5,
    max: 100,
    group: 'community',
    public: true,
  },
  {
    key: 'post_interval_seconds',
    label: '发帖/回复最小间隔（秒）',
    type: 'number',
    default: 15,
    min: 0,
    max: 600,
    group: 'community',
  },
  {
    key: 'post_min_solved',
    label: '发帖所需最少通过题数',
    type: 'number',
    default: 0,
    min: 0,
    max: 100,
    group: 'community',
  },
  {
    key: 'solution_min_solved',
    label: '发题解所需最少通过题数',
    type: 'number',
    default: 0,
    min: 0,
    max: 50,
    group: 'community',
  },
  {
    key: 'banned_words',
    label: '敏感词列表',
    type: 'json',
    default: '[]',
    group: 'community',
    description: '命中的帖子将被拒绝发布',
  },
  {
    key: 'enable_problem_solution_visible',
    label: '未通过题目即可查看题解',
    type: 'boolean',
    default: true,
    group: 'community',
    public: true,
  },
  {
    key: 'board_names',
    label: '讨论板块',
    type: 'json',
    default: '[{"slug":"general","name":"综合讨论","description":"随便聊聊"},{"slug":"algorithm","name":"算法讨论","description":"算法与数据结构"},{"slug":"help","name":"求助问答","description":"遇到问题？来这里提问"},{"slug":"contest","name":"比赛讨论","description":"比赛相关话题"},{"slug":"announce","name":"站务公告","description":"站点相关公告"}]',
    group: 'community',
  },

  // -------------------------------------------------------------- points
  {
    key: 'enable_points',
    label: '开启积分系统',
    type: 'boolean',
    default: true,
    group: 'points',
    public: true,
  },
  {
    key: 'points_per_accepted',
    label: '每通过一题获得积分',
    type: 'number',
    default: 1,
    min: 0,
    max: 100,
    group: 'points',
    description: '同一题重复通过不重复获得',
    public: true,
  },
  {
    key: 'points_first_ac_bonus',
    label: '全站首杀额外积分',
    type: 'number',
    default: 5,
    min: 0,
    max: 100,
    group: 'points',
    public: true,
  },
  {
    key: 'points_daily_login',
    label: '每日登录积分',
    type: 'number',
    default: 0,
    min: 0,
    max: 100,
    group: 'points',
  },
  {
    key: 'points_per_solution',
    label: '发布题解积分',
    type: 'number',
    default: 2,
    min: 0,
    max: 100,
    group: 'points',
  },
  {
    key: 'points_per_discussion',
    label: '发布讨论积分',
    type: 'number',
    default: 1,
    min: 0,
    max: 100,
    group: 'points',
  },
  {
    key: 'points_contest_rank1',
    label: '比赛第一名积分',
    type: 'number',
    default: 20,
    min: 0,
    max: 500,
    group: 'points',
  },
  {
    key: 'points_contest_top10',
    label: '比赛前十名积分',
    type: 'number',
    default: 5,
    min: 0,
    max: 500,
    group: 'points',
  },
  {
    key: 'points_can_be_negative',
    label: '允许积分为负数',
    type: 'boolean',
    default: false,
    group: 'points',
  },
  {
    key: 'shop_enabled',
    label: '开启商店',
    type: 'boolean',
    default: true,
    group: 'points',
    public: true,
  },
  {
    key: 'shop_order_need_review',
    label: '兑换需要管理员审核',
    type: 'boolean',
    default: true,
    group: 'points',
    description: '关闭后用户兑换立即生效',
  },
  {
    key: 'shop_refund_on_reject',
    label: '审核拒绝时退还积分',
    type: 'boolean',
    default: true,
    group: 'points',
  },
  {
    key: 'shop_default_contest_price',
    label: '默认「创建一次比赛」价格',
    type: 'number',
    default: 100,
    min: 0,
    max: 100000,
    group: 'points',
    public: true,
  },
  {
    key: 'shop_default_problem_price',
    label: '默认「出一道题」价格',
    type: 'number',
    default: 60,
    min: 0,
    max: 100000,
    group: 'points',
    public: true,
  },
  {
    key: 'shop_show_sold_out',
    label: '显示已售罄商品',
    type: 'boolean',
    default: true,
    group: 'points',
    public: true,
  },

  // ------------------------------------------------------------ security
  {
    key: 'maintenance_mode',
    label: '维护模式',
    type: 'boolean',
    default: false,
    group: 'security',
    public: true,
  },
  {
    key: 'maintenance_message',
    label: '维护提示文字',
    type: 'text',
    default: '站点正在升级维护，请稍后再来。',
    group: 'security',
    public: true,
  },
  {
    key: 'maintenance_allow_admin',
    label: '维护模式下允许管理员访问',
    type: 'boolean',
    default: true,
    group: 'security',
  },
  {
    key: 'rate_limit_per_minute',
    label: 'API 每分钟请求上限',
    type: 'number',
    default: 1200,
    min: 30,
    max: 100000,
    group: 'security',
    description: '每个 IP 每分钟允许的请求数，浏览器浏览一个页面通常会发起 5~10 个请求',
  },
  {
    key: 'max_upload_size_mb',
    label: '单次上传大小上限 (MB)',
    type: 'number',
    default: 64,
    min: 1,
    max: 1024,
    group: 'security',
  },
  {
    key: 'allow_zip_testdata',
    label: '允许上传 ZIP 测试数据',
    type: 'boolean',
    default: true,
    group: 'security',
  },
  {
    key: 'blocked_ips',
    label: 'IP 黑名单',
    type: 'json',
    default: '[]',
    group: 'security',
  },
  {
    key: 'enable_audit_log',
    label: '记录管理操作日志',
    type: 'boolean',
    default: true,
    group: 'security',
  },
  {
    key: 'force_https',
    label: '强制 HTTPS',
    type: 'boolean',
    default: false,
    group: 'security',
  },

  // ---------------------------------------------------------------- mail
  {
    key: 'smtp_enabled',
    label: '启用邮件通知',
    type: 'boolean',
    default: false,
    group: 'mail',
  },
  {
    key: 'smtp_host',
    label: 'SMTP 服务器',
    type: 'string',
    default: '',
    group: 'mail',
    placeholder: 'smtp.example.com',
  },
  {
    key: 'smtp_port',
    label: 'SMTP 端口',
    type: 'number',
    default: 465,
    min: 1,
    max: 65535,
    group: 'mail',
  },
  {
    key: 'smtp_secure',
    label: '使用 SSL/TLS',
    type: 'boolean',
    default: true,
    group: 'mail',
  },
  {
    key: 'smtp_user',
    label: 'SMTP 用户名',
    type: 'string',
    default: '',
    group: 'mail',
  },
  {
    key: 'smtp_password',
    label: 'SMTP 密码',
    type: 'password',
    default: '',
    group: 'mail',
    secret: true,
  },
  {
    key: 'smtp_from',
    label: '发件人地址',
    type: 'string',
    default: '',
    group: 'mail',
  },
  {
    key: 'notify_on_reply',
    label: '回复时站内信通知',
    type: 'boolean',
    default: true,
    group: 'mail',
  },
  {
    key: 'notify_on_judge',
    label: '评测完成站内信通知',
    type: 'boolean',
    default: false,
    group: 'mail',
  },
  {
    key: 'notify_on_shop',
    label: '订单状态变化通知',
    type: 'boolean',
    default: true,
    group: 'mail',
  },

  // --------------------------------------------------------------- legal
  {
    key: 'copyright',
    label: '版权信息',
    type: 'string',
    default: '',
    group: 'legal',
    description: '显示在页脚「Powered by OGOJ」右侧，留空则不显示（可填 © 2026 你的组织）',
    public: true,
  },
  {
    key: 'license',
    label: '开源协议',
    type: 'string',
    default: 'AGPL-3.0',
    group: 'legal',
    public: true,
  },
  {
    key: 'about_page',
    label: '关于页面内容',
    type: 'text',
    default: '## 关于 OGOJ\n\nOGOJ（Oganesson Online Judge）是一个完全开源的在线评测系统。',
    group: 'legal',
    public: true,
  },
  {
    key: 'terms_page',
    label: '用户协议',
    type: 'text',
    default: '使用本站即表示你同意遵守社区规范，不得提交违规内容。',
    group: 'legal',
    public: true,
  },
  {
    key: 'privacy_page',
    label: '隐私政策',
    type: 'text',
    default: '我们仅收集运行 OJ 所必需的信息，不会向第三方出售你的数据。',
    group: 'legal',
    public: true,
  },

  // --------------------------------------------------------- maintenance
  {
    key: 'auto_backup',
    label: '自动备份数据库',
    type: 'boolean',
    default: true,
    group: 'maintenance',
  },
  {
    key: 'backup_interval_hours',
    label: '备份间隔（小时）',
    type: 'number',
    default: 24,
    min: 1,
    max: 720,
    group: 'maintenance',
  },
  {
    key: 'backup_keep',
    label: '保留备份份数',
    type: 'number',
    default: 10,
    min: 1,
    max: 365,
    group: 'maintenance',
  },
  {
    key: 'judge_log_keep_days',
    label: '评测日志保留天数',
    type: 'number',
    default: 30,
    min: 1,
    max: 3650,
    group: 'maintenance',
  },
  {
    key: 'index_now',
    label: '首页统计口径',
    type: 'select',
    default: 'all',
    group: 'maintenance',
    options: [
      { value: 'all', label: '全部数据' },
      { value: 'public', label: '仅公开数据' },
    ],
  },
  {
    key: 'cache_ttl_seconds',
    label: '页面缓存时间（秒）',
    type: 'number',
    default: 30,
    min: 0,
    max: 3600,
    group: 'maintenance',
  },
];

/** OAuth2 provider presets: the default endpoints are pre-filled, the admin only
 *  needs to paste the client id / secret issued by the provider. */
export interface OAuthPreset {
  id: string;
  name: string;
  authorizeUrl: string;
  tokenUrl: string;
  userInfoUrl: string;
  scope: string;
  hint: string;
}

export const OAUTH_PRESETS: OAuthPreset[] = [
  {
    id: 'github',
    name: 'GitHub',
    authorizeUrl: 'https://github.com/login/oauth/authorize',
    tokenUrl: 'https://github.com/login/oauth/access_token',
    userInfoUrl: 'https://api.github.com/user',
    scope: 'read:user user:email',
    hint: '在 GitHub → Settings → Developer settings → OAuth Apps 创建应用，回调地址填写 {site}/api/auth/oauth/github/callback',
  },
  {
    id: 'gitee',
    name: 'Gitee 码云',
    authorizeUrl: 'https://gitee.com/oauth/authorize',
    tokenUrl: 'https://gitee.com/oauth/token',
    userInfoUrl: 'https://gitee.com/api/v5/user',
    scope: 'user_info',
    hint: '在 Gitee → 设置 → 第三方应用 创建应用，回调地址填写 {site}/api/auth/oauth/gitee/callback',
  },
  {
    id: 'google',
    name: 'Google',
    authorizeUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
    tokenUrl: 'https://oauth2.googleapis.com/token',
    userInfoUrl: 'https://www.googleapis.com/oauth2/v3/userinfo',
    scope: 'openid email profile',
    hint: '在 Google Cloud Console → API 和服务 → 凭据 创建 OAuth 客户端，回调地址填写 {site}/api/auth/oauth/google/callback',
  },
  {
    id: 'custom',
    name: '自定义 OAuth2',
    authorizeUrl: '',
    tokenUrl: '',
    userInfoUrl: '',
    scope: 'read',
    hint: '适用于自建 OAuth2 服务（如自建 GitLab、Authentik 等），需填写授权 / 令牌 / 用户信息三个地址；用户信息接口需返回 id、name、email、avatar_url 字段。',
  },
];

const oauthFields: SettingField[] = [
  {
    key: 'oauth_enabled',
    label: '启用第三方登录',
    type: 'boolean',
    default: true,
    group: 'oauth',
    description: '总开关，关闭后所有第三方登录入口都会隐藏',
    public: true,
  },
  {
    key: 'oauth_auto_register',
    label: '允许自动注册',
    type: 'boolean',
    default: true,
    group: 'oauth',
    description: '第三方账号首次登录时自动创建本地账号',
    public: true,
  },
  {
    key: 'oauth_allow_bind',
    label: '允许已登录用户绑定',
    type: 'boolean',
    default: true,
    group: 'oauth',
    public: true,
  },
  {
    key: 'oauth_bind_by_email',
    label: '按邮箱自动绑定已有账号',
    type: 'boolean',
    default: true,
    group: 'oauth',
    description: '第三方返回的邮箱与本地账号一致时，自动绑定而不是新建账号',
  },
  {
    key: 'oauth_show_on_login',
    label: '登录页显示第三方登录按钮',
    type: 'boolean',
    default: true,
    group: 'oauth',
    public: true,
  },
  {
    key: 'oauth_default_role',
    label: '自动注册用户的角色',
    type: 'select',
    default: 'user',
    group: 'oauth',
    options: [
      { value: 'user', label: '普通用户' },
      { value: 'admin', label: '普通管理员' },
    ],
  },
  {
    key: 'oauth_redirect_base',
    label: '回调地址前缀',
    type: 'string',
    default: '',
    group: 'oauth',
    description: '留空则使用「站点信息 → 站点地址」，例如 https://oj.example.com',
    placeholder: 'https://oj.example.com',
  },
];

for (const preset of OAUTH_PRESETS) {
  oauthFields.push(
    {
      key: `oauth_${preset.id}_enabled`,
      label: `${preset.name} 登录`,
      type: 'boolean',
      default: false,
      group: 'oauth',
      description: preset.hint,
      public: true,
    },
    {
      key: `oauth_${preset.id}_client_id`,
      label: `${preset.name} Client ID`,
      type: 'string',
      default: '',
      group: 'oauth',
    },
    {
      key: `oauth_${preset.id}_client_secret`,
      label: `${preset.name} Client Secret`,
      type: 'password',
      default: '',
      group: 'oauth',
      secret: true,
    },
    {
      key: `oauth_${preset.id}_scope`,
      label: `${preset.name} Scope`,
      type: 'string',
      default: preset.scope,
      group: 'oauth',
    },
    {
      key: `oauth_${preset.id}_authorize_url`,
      label: `${preset.name} 授权地址`,
      type: 'string',
      default: preset.authorizeUrl,
      group: 'oauth',
      placeholder: preset.authorizeUrl || 'https://example.com/oauth/authorize',
    },
    {
      key: `oauth_${preset.id}_token_url`,
      label: `${preset.name} 令牌地址`,
      type: 'string',
      default: preset.tokenUrl,
      group: 'oauth',
      placeholder: preset.tokenUrl || 'https://example.com/oauth/token',
    },
    {
      key: `oauth_${preset.id}_userinfo_url`,
      label: `${preset.name} 用户信息地址`,
      type: 'string',
      default: preset.userInfoUrl,
      group: 'oauth',
      placeholder: preset.userInfoUrl || 'https://example.com/oauth/userinfo',
    },
  );
}

const achievementFields: SettingField[] = [
  {
    key: 'achievement_enable',
    label: '开启成就系统',
    type: 'boolean',
    default: true,
    group: 'achievement',
    public: true,
  },
  {
    key: 'achievement_notify',
    label: '解锁成就发送站内信',
    type: 'boolean',
    default: true,
    group: 'achievement',
  },
  {
    key: 'achievement_show_locked',
    label: '个人主页显示未解锁徽章',
    type: 'boolean',
    default: true,
    group: 'achievement',
    public: true,
  },
];

const ticketFields: SettingField[] = [
  {
    key: 'enable_tickets',
    label: '开启工单系统',
    type: 'boolean',
    default: true,
    group: 'ticket',
    description: '关闭后用户无法提交新工单，已存在的工单仍可在后台查看',
    public: true,
  },
  {
    key: 'ticket_show_entry',
    label: '在前台显示工单入口',
    type: 'boolean',
    default: true,
    group: 'ticket',
    description: '顶栏图标、页脚与帮助页的工单入口',
    public: true,
  },
  {
    key: 'ticket_categories',
    label: '工单分类',
    type: 'json',
    default:
      '[{"value":"bug","label":"站点故障 / Bug","description":"页面报错、功能异常、评测机问题"},{"value":"problem","label":"题目问题","description":"题面错误、数据有误、缺少题解"},{"value":"account","label":"账号问题","description":"登录异常、密码、封禁申诉、改名"},{"value":"contest","label":"比赛相关","description":"比赛时间、权限、成绩申诉"},{"value":"report","label":"举报违规","description":"抄袭、恶意提交、违规内容"},{"value":"suggestion","label":"功能建议","description":"希望 OGOJ 增加的功能"},{"value":"other","label":"其它","description":"不属于以上分类的问题"}]',
    group: 'ticket',
    public: true,
  },
  {
    key: 'ticket_allow_priority',
    label: '允许用户选择优先级',
    type: 'boolean',
    default: true,
    group: 'ticket',
    public: true,
  },
  {
    key: 'ticket_max_content_kb',
    label: '工单内容长度上限 (KB)',
    type: 'number',
    default: 8,
    min: 1,
    max: 128,
    group: 'ticket',
    public: true,
  },
  {
    key: 'ticket_rate_limit_seconds',
    label: '两次提交工单的最小间隔（秒）',
    type: 'number',
    default: 60,
    min: 0,
    max: 86400,
    group: 'ticket',
  },
  {
    key: 'ticket_max_open',
    label: '每个用户同时开启的工单上限',
    type: 'number',
    default: 5,
    min: 0,
    max: 100,
    group: 'ticket',
    description: '0 表示不限制',
    public: true,
  },
  {
    key: 'ticket_auto_close_days',
    label: '已解决工单自动关闭天数',
    type: 'number',
    default: 7,
    min: 0,
    max: 365,
    group: 'ticket',
    description: '0 表示不自动关闭',
  },
  {
    key: 'ticket_allow_rating',
    label: '允许用户评价处理结果',
    type: 'boolean',
    default: true,
    group: 'ticket',
    public: true,
  },
  {
    key: 'ticket_notify_admin',
    label: '新工单通知管理员',
    type: 'boolean',
    default: true,
    group: 'ticket',
  },
  {
    key: 'ticket_notify_user',
    label: '工单有新回复通知用户',
    type: 'boolean',
    default: true,
    group: 'ticket',
  },
  {
    key: 'ticket_notice',
    label: '工单页提示文字',
    type: 'text',
    default:
      '提交工单前请先查看帮助中心，并尽量提供题目编号、提交编号、截图与复现步骤，方便我们更快定位问题。',
    group: 'ticket',
    public: true,
  },
  {
    key: 'ticket_list_page_size',
    label: '工单列表每页数量',
    type: 'number',
    default: 20,
    min: 5,
    max: 100,
    group: 'ticket',
    public: true,
  },
];

SETTINGS.push(...oauthFields, ...achievementFields, ...ticketFields);

export const SETTING_MAP: Record<string, SettingField> = Object.fromEntries(
  SETTINGS.map((s) => [s.key, s]),
);

export const PUBLIC_SETTING_KEYS = SETTINGS.filter((s) => s.public).map((s) => s.key);

export function defaultSettings(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const field of SETTINGS) out[field.key] = serializeSetting(field.default, field.type);
  return out;
}

export function serializeSetting(value: unknown, type: SettingType): string {
  if (type === 'boolean') return value ? 'true' : 'false';
  if (type === 'json') {
    return typeof value === 'string' ? value : JSON.stringify(value ?? []);
  }
  return String(value ?? '');
}

export function parseSetting(raw: string | undefined, field: SettingField): unknown {
  if (raw === undefined) return field.default;
  switch (field.type) {
    case 'boolean':
      return raw === 'true' || raw === '1';
    case 'number': {
      const num = Number(raw);
      return Number.isFinite(num) ? num : Number(field.default);
    }
    case 'json': {
      try {
        return JSON.parse(raw);
      } catch {
        return field.default;
      }
    }
    default:
      return raw;
  }
}
