/**
 * PostgreSQL 数据访问层（OGOJ 3.0 起由 SQLite 迁移到 PostgreSQL）。
 *
 * 为了不改动上千处业务里已有的 SQL 写法，这里保留 `all / get / run / count / tx`
 * 这套接口，并在底层做两件事：
 *   1. 把 SQLite 风格的 SQL（`?` 占位符、datetime('now')、INSERT OR IGNORE 等）翻译成 PostgreSQL 语法；
 *   2. 用 AsyncLocalStorage 让嵌套事务复用同一个连接（保持旧 tx 的语义）。
 */
import { AsyncLocalStorage } from 'node:async_hooks';
import { execFile } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { promisify } from 'node:util';
import { Pool, types, type PoolClient } from 'pg';
import { config } from '../config.js';
import { DEFAULT_DIFFICULTIES } from '../lib/difficulty-defaults.js';

const execFileAsync = promisify(execFile);

/** 时间 / 计数保持与 SQLite 时代一致的返回形态（字符串时间、数字计数） */
types.setTypeParser(1114, (value) => value); // timestamp
types.setTypeParser(1184, (value) => value); // timestamptz
types.setTypeParser(1082, (value) => value); // date
types.setTypeParser(20, (value) => Number(value)); // bigint
types.setTypeParser(1700, (value) => Number(value)); // numeric

export const pool = new Pool({
  connectionString: config.databaseUrl,
  max: config.databasePoolSize,
  idleTimeoutMillis: 30_000,
  connectionTimeoutMillis: 10_000,
});

pool.on('error', (error) => {
  console.error('[ogoj] postgres pool error:', error.message);
});

const txStorage = new AsyncLocalStorage<PoolClient>();

/* ------------------------------------------------------------------ SQL 翻译 */

/** 逐段处理 SQL，跳过字符串字面量与注释，避免误伤里面的字符 */
function mapSql(source: string, replacer: (segment: string) => string): string {
  let output = '';
  let index = 0;
  let quote: string | null = null;
  while (index < source.length) {
    const ch = source[index]!;
    if (quote) {
      output += ch;
      if (ch === quote) {
        if (source[index + 1] === quote) {
          output += source[index + 1];
          index += 2;
          continue;
        }
        quote = null;
      }
      index += 1;
      continue;
    }
    if (ch === "'" || ch === '"') {
      quote = ch;
      output += ch;
      index += 1;
      continue;
    }
    if (ch === '-' && source[index + 1] === '-') {
      const end = source.indexOf('\n', index);
      const stop = end === -1 ? source.length : end;
      output += source.slice(index, stop);
      index = stop;
      continue;
    }
    if (ch === '/' && source[index + 1] === '*') {
      const end = source.indexOf('*/', index);
      const stop = end === -1 ? source.length : end + 2;
      output += source.slice(index, stop);
      index = stop;
      continue;
    }
    let end = index + 1;
    while (end < source.length) {
      const next = source[end]!;
      if (
        next === "'" ||
        next === '"' ||
        (next === '-' && source[end + 1] === '-') ||
        (next === '/' && source[end + 1] === '*')
      ) {
        break;
      }
      end += 1;
    }
    output += replacer(source.slice(index, end));
    index = end;
  }
  return output;
}

/** 把 SQLite 专属写法翻译成 PostgreSQL */
export function translateSql(sql: string): string {
  let out = sql;
  const isDdl = /^\s*(create|alter)\s+table/im.test(sql);

  out = out.replace(
    /\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi,
    'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
  );
  out = out.replace(/\bAUTOINCREMENT\b/gi, '');

  out = out.replace(/datetime\(\s*'now'\s*\)/gi, "(now() at time zone 'utc')");
  out = out.replace(/date\(\s*'now'\s*\)/gi, "(now() at time zone 'utc')::date");
  out = out.replace(/datetime\(\s*'now'\s*,\s*'([^']+)'\s*\)/gi, (_m, offset: string) => {
    const cleaned = offset
      .replace(/^\+\s*/, '')
      .replace(/\bday(s)?\b/i, 'days')
      .replace(/\bhour(s)?\b/i, 'hours')
      .replace(/\bminute(s)?\b/i, 'minutes')
      .replace(/\bmonth(s)?\b/i, 'months')
      .replace(/\byear(s)?\b/i, 'years');
    return `((now() at time zone 'utc') + interval '${cleaned}')`;
  });
  // 偏移量是参数（datetime('now', ?)）时，由 PostgreSQL 把参数当 interval
  out = out.replace(
    /datetime\(\s*'now'\s*,\s*(\?[^)]*)\)/gi,
    "((now() at time zone 'utc') + ($1)::interval)",
  );
  out = out.replace(/CURRENT_TIMESTAMP/gi, "(now() at time zone 'utc')");
  out = out.replace(/strftime\(\s*'%Y-%m'\s*,\s*([^)]+)\)/gi, "to_char($1, 'YYYY-MM')");
  out = out.replace(/strftime\(\s*'%Y-%m-%d'\s*,\s*([^)]+)\)/gi, "to_char($1, 'YYYY-MM-DD')");
  out = out.replace(/strftime\(\s*'%H'\s*,\s*([^)]+)\)/gi, "to_char($1, 'HH24')");
  out = out.replace(/strftime\(\s*'%Y'\s*,\s*([^)]+)\)/gi, "to_char($1, 'YYYY')");
  out = out.replace(/strftime\(\s*'%m'\s*,\s*([^)]+)\)/gi, "to_char($1, 'MM')");

  out = out.replace(/\bIFNULL\s*\(/gi, 'COALESCE(');
  out = out.replace(/\bGROUP_CONCAT\s*\(/gi, 'string_agg(');
  // SQLite 的标量 MAX(a, b) → PostgreSQL 的 GREATEST(a, b)
  out = out.replace(/\bMAX\s*\(\s*0\s*,/gi, 'GREATEST(0,');
  out = out.replace(/\bINSERT\s+OR\s+IGNORE\s+INTO\b/gi, 'INSERT INTO');

  // date('now', '-13 days') 这类带偏移的写法
  out = out.replace(
    /date\(\s*'now'\s*,\s*'([^']+)'\s*\)/gi,
    (_m, offset: string) => `((now() at time zone 'utc')::date + interval '${offset.trim()}')`,
  );

  // SQLite 用 TEXT 存时间，PostgreSQL 下改成 TIMESTAMP（返回仍是字符串，由类型解析器保证）
  if (isDdl) {
    out = out.replace(
      /\bTEXT\s+NOT\s+NULL\s+DEFAULT\s+\(now\(\) at time zone 'utc'\)/gi,
      "TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc')",
    );
    out = out.replace(
      /\bTEXT\s+DEFAULT\s+\(now\(\) at time zone 'utc'\)/gi,
      "TIMESTAMP DEFAULT (now() at time zone 'utc')",
    );
    // 常见的日期列（xxx_at / xxx_time / xxx_date）统一用 TIMESTAMP
    out = out.replace(/(\b[a-z_]+(?:_at|_time|_date))\s+TEXT\b/gi, '$1 TIMESTAMP');
  }

  // SQLite 的 LIKE 默认大小写不敏感
  out = mapSql(out, (segment) => segment.replace(/\bLIKE\b/gi, 'ILIKE'));

  return out;
}

function isInsertOrIgnore(sql: string): boolean {
  return /\bINSERT\s+OR\s+IGNORE\b/i.test(sql);
}

export type SqlParams = Record<string, unknown> | unknown[];

function bind(sql: string, params?: SqlParams): { text: string; values: unknown[] } {
  let text = translateSql(sql);
  if (isInsertOrIgnore(sql) && !/\bON\s+CONFLICT\b/i.test(text)) {
    text = `${text.trim().replace(/;$/, '')} ON CONFLICT DO NOTHING`;
  }
  if (!params) return { text, values: [] };

  if (Array.isArray(params)) {
    let index = 0;
    const withPlaceholders = mapSql(text, (segment) => segment.replace(/\?/g, () => `$${++index}`));
    return { text: withPlaceholders, values: params };
  }

  const values: unknown[] = [];
  const withNamed = mapSql(text, (segment) =>
    segment.replace(/[@:$]([a-zA-Z_][a-zA-Z0-9_]*)/g, (_m, name: string) => {
      values.push((params as Record<string, unknown>)[name]);
      return `$${values.length}`;
    }),
  );
  return { text: withNamed, values };
}

function connection(): Pool | PoolClient {
  return txStorage.getStore() ?? pool;
}

/* ------------------------------------------------------------------ 查询接口 */

export async function all<T = any>(sql: string, params?: SqlParams): Promise<T[]> {
  const { text, values } = bind(sql, params);
  const result = await connection().query(text, values);
  return result.rows as T[];
}

export async function get<T = any>(sql: string, params?: SqlParams): Promise<T | undefined> {
  const rows = await all<T>(sql, params);
  return rows[0];
}

export interface RunResult {
  changes: number;
  lastInsertRowid: number;
  rows: any[];
}

/** 哪些表有自增 id 列（INSERT 才能安全地加 RETURNING id） */
const tableHasId = new Map<string, boolean>();

async function insertTargetHasId(sql: string): Promise<boolean> {
  const match = /^\s*insert\s+into\s+"?([a-zA-Z_][a-zA-Z0-9_]*)"?/i.exec(sql);
  if (!match) return false;
  const table = match[1]!;
  const cached = tableHasId.get(table);
  if (cached !== undefined) return cached;
  const row = await get<{ c: number }>(
    `SELECT COUNT(*) AS c FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = ? AND column_name = 'id'`,
    [table],
  );
  const has = Number(row?.c ?? 0) > 0;
  tableHasId.set(table, has);
  return has;
}

/**
 * 执行写入语句。INSERT 会自动补 `RETURNING id`，
 * 调用方继续用 `(await run(...)).lastInsertRowid` 就能拿到自增主键。
 */
export async function run(sql: string, params?: SqlParams): Promise<RunResult> {
  const bound = bind(sql, params);
  const isInsert = /^\s*insert\s/i.test(bound.text);
  const hasReturning = /\breturning\b/i.test(bound.text);
  // 事务里语句一旦报错整个事务就废了，所以先确认目标表有没有 id 列，再决定是否加 RETURNING
  const wantsReturning = isInsert && !hasReturning && (await insertTargetHasId(bound.text));
  const text = wantsReturning ? `${bound.text} RETURNING id` : bound.text;
  const result = await connection().query(text, bound.values);
  return {
    changes: result.rowCount ?? 0,
    lastInsertRowid: result.rows[0]?.id === undefined ? 0 : Number(result.rows[0].id),
    rows: result.rows,
  };
}

export async function pluck<T = any>(sql: string, params?: SqlParams): Promise<T | undefined> {
  const row = await get<Record<string, any>>(sql, params);
  if (!row) return undefined;
  return Object.values(row)[0] as T;
}

export async function count(sql: string, params?: SqlParams): Promise<number> {
  return Number((await pluck<number>(sql, params)) ?? 0);
}

/** 事务：嵌套调用复用同一个连接，与旧版 tx 语义一致 */
export async function tx<T>(fn: () => Promise<T>): Promise<T> {
  if (txStorage.getStore()) return fn();
  const client = await pool.connect();
  try {
    await client.query('begin');
    const result = await txStorage.run(client, fn);
    await client.query('commit');
    return result;
  } catch (error) {
    try {
      await client.query('rollback');
    } catch {
      /* ignore */
    }
    throw error;
  } finally {
    client.release();
  }
}

/* ------------------------------------------------------------------ 迁移与工具 */

/** 老库补列（幂等）：列已存在会报错并跳过，不影响启动。 */
const COLUMN_MIGRATIONS: string[] = [
  `ALTER TABLE users ADD COLUMN phone TEXT`,
  `ALTER TABLE users ADD COLUMN phone_verified INTEGER NOT NULL DEFAULT 0`,
];

const INDEX_MIGRATIONS: string[] = [
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_users_phone ON users(phone) WHERE phone IS NOT NULL`,
];

async function ensureColumns(): Promise<void> {
  for (const statement of COLUMN_MIGRATIONS) {
    try {
      await pool.query(statement);
    } catch {
      /* 列已存在 */
    }
  }
  for (const statement of INDEX_MIGRATIONS) {
    try {
      await pool.query(statement);
    } catch {
      /* 索引已存在 */
    }
  }
}

export async function migrate(): Promise<void> {
  const { SCHEMA_SQL } = await import('./schema.js');
  await pool.query(translateSql(SCHEMA_SQL));
  // 用户名查重区分大小写：早期版本建过一条忽略大小写的唯一索引，这里确保删掉它
  try {
    await pool.query('DROP INDEX IF EXISTS idx_users_username_lower');
  } catch (error) {
    console.warn('[ogoj] 清理用户名大小写唯一索引失败：', (error as Error).message);
  }
  await ensureColumns();
  const existing = await count('SELECT COUNT(*) AS c FROM difficulties');
  if (!existing) {
    for (const item of DEFAULT_DIFFICULTIES) {
      await run('INSERT INTO difficulties (level, name, color, color_dark) VALUES (?, ?, ?, ?)', [
        item.level,
        item.name,
        item.color,
        item.colorDark,
      ]);
    }
  }
}

export async function tableExists(name: string): Promise<boolean> {
  const row = await get<{ c: number }>(
    `SELECT COUNT(*) AS c FROM information_schema.tables WHERE table_schema = 'public' AND table_name = ?`,
    [name],
  );
  return Number(row?.c ?? 0) > 0;
}

export function nowIso(): string {
  return new Date().toISOString().replace('T', ' ').slice(0, 19);
}

/** 用 pg_dump 备份数据库，落在 data/backups 下 */
export async function backupDatabase(label = 'manual'): Promise<string> {
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const file = path.join(config.paths.backups, `ogoj-${label}-${stamp}.sql`);
  await execFileAsync('pg_dump', ['--no-owner', '--no-privileges', '-f', file, config.databaseUrl]);
  return file;
}

export function listBackups(): { file: string; size: number; created_at: string }[] {
  if (!fs.existsSync(config.paths.backups)) return [];
  return fs
    .readdirSync(config.paths.backups)
    .filter((f) => f.endsWith('.sql') || f.endsWith('.db'))
    .map((f) => {
      const full = path.join(config.paths.backups, f);
      const stat = fs.statSync(full);
      return { file: f, size: stat.size, created_at: stat.mtime.toISOString() };
    })
    .sort((a, b) => b.created_at.localeCompare(a.created_at));
}

export async function closePool(): Promise<void> {
  await pool.end();
}
